export const Clock_Options = [
    {
        option: 'World Clock',
        fileName: 'WorldClock',
        desc: 'Track time around the world.',
        icon: 'Globe',

    },
    {
        option: 'Alarms',
        fileName: 'Alarms',
        desc: 'Wake up on time, everytime.',
        icon: 'Bell',

    },
    {
        option: 'Stopwatch',
        fileName: 'Stopwatch',
        desc: 'Manage Stopwatch.',
        icon: 'ClockFading',
    }, {
        option: 'Timers',
        fileName: 'Timers',
        desc: 'Manage Timers.',
        icon: 'ClockFading',
    }
]


export const WORLD_CITIES = [
  {
    city: "Abu Dhabi",
    countryCode: "AE",
    country: "United Arab Emirates",
    gmtOffset: "+4 HRS",
    timeZone: "Asia/Dubai",
  },
  {
    city: "Abuja",
    countryCode: "NG",
    country: "Nigeria",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Lagos",
  },
  {
    city: "Accra",
    countryCode: "GH",
    country: "Ghana",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Accra",
  },
  {
    city: "Addis Ababa",
    countryCode: "ET",
    country: "Ethiopia",
    gmtOffset: "+3 HRS",
    timeZone: "Africa/Addis_Ababa",
  },
  {
    city: "Algiers",
    countryCode: "DZ",
    country: "Algeria",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Algiers",
  },
  {
    city: "Amman",
    countryCode: "JO",
    country: "Jordan",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Amman",
  },
  {
    city: "Amsterdam",
    countryCode: "NL",
    country: "Netherlands",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Amsterdam",
  },
  {
    city: "Andorra la Vella",
    countryCode: "AD",
    country: "Andorra",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Andorra",
  },
  {
    city: "Antananarivo",
    countryCode: "MG",
    country: "Madagascar",
    gmtOffset: "+3 HRS",
    timeZone: "Indian/Antananarivo",
  },
  {
    city: "Apia",
    countryCode: "WS",
    country: "Samoa",
    gmtOffset: "+13 HRS",
    timeZone: "Pacific/Apia",
  },
  {
    city: "Asmara",
    countryCode: "ER",
    country: "Eritrea",
    gmtOffset: "+3 HRS",
    timeZone: "Africa/Asmara",
  },
  {
    city: "Astana",
    countryCode: "KZ",
    country: "Kazakhstan",
    gmtOffset: "+5 HRS",
    timeZone: "Asia/Almaty",
  },
  {
    city: "Asunción",
    countryCode: "PY",
    country: "Paraguay",
    gmtOffset: "-4 HRS",
    timeZone: "America/Asuncion",
  },
  {
    city: "Athens",
    countryCode: "GR",
    country: "Greece",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Athens",
  },
  {
    city: "Baghdad",
    countryCode: "IQ",
    country: "Iraq",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Baghdad",
  },
  {
    city: "Baku",
    countryCode: "AZ",
    country: "Azerbaijan",
    gmtOffset: "+4 HRS",
    timeZone: "Asia/Baku",
  },
  {
    city: "Bamako",
    countryCode: "ML",
    country: "Mali",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Bamako",
  },
  {
    city: "Bandar Seri Begawan",
    countryCode: "BN",
    country: "Brunei",
    gmtOffset: "+8 HRS",
    timeZone: "Asia/Brunei",
  },
  {
    city: "Bangkok",
    countryCode: "TH",
    country: "Thailand",
    gmtOffset: "+7 HRS",
    timeZone: "Asia/Bangkok",
  },
  {
    city: "Bangui",
    countryCode: "CF",
    country: "Central African Republic",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Bangui",
  },
  {
    city: "Banjul",
    countryCode: "GM",
    country: "Gambia",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Banjul",
  },
  {
    city: "Basseterre",
    countryCode: "KN",
    country: "Saint Kitts and Nevis",
    gmtOffset: "-4 HRS",
    timeZone: "America/St_Kitts",
  },
  {
    city: "Beijing",
    countryCode: "CN",
    country: "China",
    gmtOffset: "+8 HRS",
    timeZone: "Asia/Shanghai",
  },
  {
    city: "Beirut",
    countryCode: "LB",
    country: "Lebanon",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Beirut",
  },
  {
    city: "Belgrade",
    countryCode: "RS",
    country: "Serbia",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Belgrade",
  },
  {
    city: "Belmopan",
    countryCode: "BZ",
    country: "Belize",
    gmtOffset: "-6 HRS",
    timeZone: "America/Belize",
  },
  {
    city: "Berlin",
    countryCode: "DE",
    country: "Germany",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Berlin",
  },
  {
    city: "Bern",
    countryCode: "CH",
    country: "Switzerland",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Zurich",
  },
  {
    city: "Bishkek",
    countryCode: "KG",
    country: "Kyrgyzstan",
    gmtOffset: "+6 HRS",
    timeZone: "Asia/Bishkek",
  },
  {
    city: "Bissau",
    countryCode: "GW",
    country: "Guinea-Bissau",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Bissau",
  },
  {
    city: "Bogotá",
    countryCode: "CO",
    country: "Colombia",
    gmtOffset: "-5 HRS",
    timeZone: "America/Bogota",
  },
  {
    city: "Bratislava",
    countryCode: "SK",
    country: "Slovakia",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Bratislava",
  },
  {
    city: "Brasília",
    countryCode: "BR",
    country: "Brazil",
    gmtOffset: "-3 HRS",
    timeZone: "America/Sao_Paulo",
  },
  {
    city: "Bridgetown",
    countryCode: "BB",
    country: "Barbados",
    gmtOffset: "-4 HRS",
    timeZone: "America/Barbados",
  },
  {
    city: "Brussels",
    countryCode: "BE",
    country: "Belgium",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Brussels",
  },
  {
    city: "Bucharest",
    countryCode: "RO",
    country: "Romania",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Bucharest",
  },
  {
    city: "Budapest",
    countryCode: "HU",
    country: "Hungary",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Budapest",
  },
  {
    city: "Buenos Aires",
    countryCode: "AR",
    country: "Argentina",
    gmtOffset: "-3 HRS",
    timeZone: "America/Argentina/Buenos_Aires",
  },
  {
    city: "Cairo",
    countryCode: "EG",
    country: "Egypt",
    gmtOffset: "+3 HRS",
    timeZone: "Africa/Cairo",
  },
  {
    city: "Canberra",
    countryCode: "AU",
    country: "Australia",
    gmtOffset: "+10 HRS",
    timeZone: "Australia/Sydney",
  },
  {
    city: "Castries",
    countryCode: "LC",
    country: "Saint Lucia",
    gmtOffset: "-4 HRS",
    timeZone: "America/St_Lucia",
  },
  {
    city: "Chișinău",
    countryCode: "MD",
    country: "Moldova",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Chisinau",
  },
  {
    city: "Colombo",
    countryCode: "LK",
    country: "Sri Lanka",
    gmtOffset: "+5:30 HRS",
    timeZone: "Asia/Colombo",
  },
  {
    city: "Conakry",
    countryCode: "GN",
    country: "Guinea",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Conakry",
  },
  {
    city: "Copenhagen",
    countryCode: "DK",
    country: "Denmark",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Copenhagen",
  },
  {
    city: "Dakar",
    countryCode: "SN",
    country: "Senegal",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Dakar",
  },
  {
    city: "Damascus",
    countryCode: "SY",
    country: "Syria",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Damascus",
  },
  {
    city: "Dhaka",
    countryCode: "BD",
    country: "Bangladesh",
    gmtOffset: "+6 HRS",
    timeZone: "Asia/Dhaka",
  },
  {
    city: "Dili",
    countryCode: "TL",
    country: "Timor-Leste",
    gmtOffset: "+9 HRS",
    timeZone: "Asia/Dili",
  },
  {
    city: "Djibouti",
    countryCode: "DJ",
    country: "Djibouti",
    gmtOffset: "+3 HRS",
    timeZone: "Africa/Djibouti",
  },
  {
    city: "Dodoma",
    countryCode: "TZ",
    country: "Tanzania",
    gmtOffset: "+3 HRS",
    timeZone: "Africa/Dar_es_Salaam",
  },
  {
    city: "Doha",
    countryCode: "QA",
    country: "Qatar",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Qatar",
  },
  {
    city: "Dublin",
    countryCode: "IE",
    country: "Ireland",
    gmtOffset: "+1 HRS",
    timeZone: "Europe/Dublin",
  },
  {
    city: "Dushanbe",
    countryCode: "TJ",
    country: "Tajikistan",
    gmtOffset: "+5 HRS",
    timeZone: "Asia/Dushanbe",
  },
  {
    city: "Freetown",
    countryCode: "SL",
    country: "Sierra Leone",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Freetown",
  },
  {
    city: "Funafuti",
    countryCode: "TV",
    country: "Tuvalu",
    gmtOffset: "+12 HRS",
    timeZone: "Pacific/Funafuti",
  },
  {
    city: "Gaborone",
    countryCode: "BW",
    country: "Botswana",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Gaborone",
  },
  {
    city: "Georgetown",
    countryCode: "GY",
    country: "Guyana",
    gmtOffset: "-4 HRS",
    timeZone: "America/Guyana",
  },
  {
    city: "Gitega",
    countryCode: "BI",
    country: "Burundi",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Bujumbura",
  },
  {
    city: "Guatemala City",
    countryCode: "GT",
    country: "Guatemala",
    gmtOffset: "-6 HRS",
    timeZone: "America/Guatemala",
  },
  {
    city: "Hanoi",
    countryCode: "VN",
    country: "Vietnam",
    gmtOffset: "+7 HRS",
    timeZone: "Asia/Ho_Chi_Minh",
  },
  {
    city: "Harare",
    countryCode: "ZW",
    country: "Zimbabwe",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Harare",
  },
  {
    city: "Havana",
    countryCode: "CU",
    country: "Cuba",
    gmtOffset: "-4 HRS",
    timeZone: "America/Havana",
  },
  {
    city: "Helsinki",
    countryCode: "FI",
    country: "Finland",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Helsinki",
  },
  {
    city: "Honiara",
    countryCode: "SB",
    country: "Solomon Islands",
    gmtOffset: "+11 HRS",
    timeZone: "Pacific/Guadalcanal",
  },
  {
    city: "Islamabad",
    countryCode: "PK",
    country: "Pakistan",
    gmtOffset: "+5 HRS",
    timeZone: "Asia/Karachi",
  },
  {
    city: "Istanbul",
    countryCode: "TR",
    country: "Türkiye",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Istanbul",
  },
  {
    city: "Jakarta",
    countryCode: "ID",
    country: "Indonesia",
    gmtOffset: "+7 HRS",
    timeZone: "Asia/Jakarta",
  },
  {
    city: "Jerusalem",
    countryCode: "IL",
    country: "Israel",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Jerusalem",
  },
  {
    city: "Johannesburg",
    countryCode: "ZA",
    country: "South Africa",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Johannesburg",
  },
  {
    city: "Juba",
    countryCode: "SS",
    country: "South Sudan",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Juba",
  },
  {
    city: "Kabul",
    countryCode: "AF",
    country: "Afghanistan",
    gmtOffset: "+4:30 HRS",
    timeZone: "Asia/Kabul",
  },
  {
    city: "Kampala",
    countryCode: "UG",
    country: "Uganda",
    gmtOffset: "+3 HRS",
    timeZone: "Africa/Kampala",
  },
  {
    city: "Kathmandu",
    countryCode: "NP",
    country: "Nepal",
    gmtOffset: "+5:45 HRS",
    timeZone: "Asia/Kathmandu",
  },
  {
    city: "Khartoum",
    countryCode: "SD",
    country: "Sudan",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Khartoum",
  },
  {
    city: "Kigali",
    countryCode: "RW",
    country: "Rwanda",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Kigali",
  },
  {
    city: "Kingston",
    countryCode: "JM",
    country: "Jamaica",
    gmtOffset: "-5 HRS",
    timeZone: "America/Jamaica",
  },
  {
    city: "Kingstown",
    countryCode: "VC",
    country: "Saint Vincent and the Grenadines",
    gmtOffset: "-4 HRS",
    timeZone: "America/St_Vincent",
  },
  {
    city: "Kinshasa",
    countryCode: "CD",
    country: "Democratic Republic of the Congo",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Kinshasa",
  },
  {
    city: "Kuala Lumpur",
    countryCode: "MY",
    country: "Malaysia",
    gmtOffset: "+8 HRS",
    timeZone: "Asia/Kuala_Lumpur",
  },
  {
    city: "Kuwait City",
    countryCode: "KW",
    country: "Kuwait",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Kuwait",
  },
  {
    city: "Kyiv",
    countryCode: "UA",
    country: "Ukraine",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Kyiv",
  },
  {
    city: "Lima",
    countryCode: "PE",
    country: "Peru",
    gmtOffset: "-5 HRS",
    timeZone: "America/Lima",
  },
  {
    city: "Lisbon",
    countryCode: "PT",
    country: "Portugal",
    gmtOffset: "+1 HRS",
    timeZone: "Europe/Lisbon",
  },
  {
    city: "Ljubljana",
    countryCode: "SI",
    country: "Slovenia",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Ljubljana",
  },
  {
    city: "Lomé",
    countryCode: "TG",
    country: "Togo",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Lome",
  },
  {
    city: "London",
    countryCode: "GB",
    country: "United Kingdom",
    gmtOffset: "+1 HRS",
    timeZone: "Europe/London",
  },
  {
    city: "Luanda",
    countryCode: "AO",
    country: "Angola",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Luanda",
  },
  {
    city: "Lusaka",
    countryCode: "ZM",
    country: "Zambia",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Lusaka",
  },
  {
    city: "Luxembourg",
    countryCode: "LU",
    country: "Luxembourg",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Luxembourg",
  },
  {
    city: "Madrid",
    countryCode: "ES",
    country: "Spain",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Madrid",
  },
  {
    city: "Majuro",
    countryCode: "MH",
    country: "Marshall Islands",
    gmtOffset: "+12 HRS",
    timeZone: "Pacific/Majuro",
  },
  {
    city: "Malabo",
    countryCode: "GQ",
    country: "Equatorial Guinea",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Malabo",
  },
  {
    city: "Malé",
    countryCode: "MV",
    country: "Maldives",
    gmtOffset: "+5 HRS",
    timeZone: "Indian/Maldives",
  },
  {
    city: "Managua",
    countryCode: "NI",
    country: "Nicaragua",
    gmtOffset: "-6 HRS",
    timeZone: "America/Managua",
  },
  {
    city: "Manama",
    countryCode: "BH",
    country: "Bahrain",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Bahrain",
  },
  {
    city: "Manila",
    countryCode: "PH",
    country: "Philippines",
    gmtOffset: "+8 HRS",
    timeZone: "Asia/Manila",
  },
  {
    city: "Maputo",
    countryCode: "MZ",
    country: "Mozambique",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Maputo",
  },
  {
    city: "Maseru",
    countryCode: "LS",
    country: "Lesotho",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Maseru",
  },
  {
    city: "Mbabane",
    countryCode: "SZ",
    country: "Eswatini",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Mbabane",
  },
  {
    city: "Mexico City",
    countryCode: "MX",
    country: "Mexico",
    gmtOffset: "-6 HRS",
    timeZone: "America/Mexico_City",
  },
  {
    city: "Minsk",
    countryCode: "BY",
    country: "Belarus",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Minsk",
  },
  {
    city: "Mogadishu",
    countryCode: "SO",
    country: "Somalia",
    gmtOffset: "+3 HRS",
    timeZone: "Africa/Mogadishu",
  },
  {
    city: "Monaco",
    countryCode: "MC",
    country: "Monaco",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Monaco",
  },
  {
    city: "Monrovia",
    countryCode: "LR",
    country: "Liberia",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Monrovia",
  },
  {
    city: "Montevideo",
    countryCode: "UY",
    country: "Uruguay",
    gmtOffset: "-3 HRS",
    timeZone: "America/Montevideo",
  },
  {
    city: "Moroni",
    countryCode: "KM",
    country: "Comoros",
    gmtOffset: "+3 HRS",
    timeZone: "Indian/Comoro",
  },
  {
    city: "Moscow",
    countryCode: "RU",
    country: "Russia",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Moscow",
  },
  {
    city: "Muscat",
    countryCode: "OM",
    country: "Oman",
    gmtOffset: "+4 HRS",
    timeZone: "Asia/Muscat",
  },
  {
    city: "N'Djamena",
    countryCode: "TD",
    country: "Chad",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Ndjamena",
  },
  {
    city: "Nairobi",
    countryCode: "KE",
    country: "Kenya",
    gmtOffset: "+3 HRS",
    timeZone: "Africa/Nairobi",
  },
  {
    city: "Nassau",
    countryCode: "BS",
    country: "Bahamas",
    gmtOffset: "-4 HRS",
    timeZone: "America/Nassau",
  },
  {
    city: "Naypyidaw",
    countryCode: "MM",
    country: "Myanmar",
    gmtOffset: "+6:30 HRS",
    timeZone: "Asia/Yangon",
  },
  {
    city: "New Delhi",
    countryCode: "IN",
    country: "India",
    gmtOffset: "+5:30 HRS",
    timeZone: "Asia/Kolkata",
  },
  {
    city: "Niamey",
    countryCode: "NE",
    country: "Niger",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Niamey",
  },
  {
    city: "Nicosia",
    countryCode: "CY",
    country: "Cyprus",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Nicosia",
  },
  {
    city: "Ngerulmud",
    countryCode: "PW",
    country: "Palau",
    gmtOffset: "+9 HRS",
    timeZone: "Pacific/Palau",
  },
  {
    city: "Nouakchott",
    countryCode: "MR",
    country: "Mauritania",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Nouakchott",
  },
  {
    city: "Nuku'alofa",
    countryCode: "TO",
    country: "Tonga",
    gmtOffset: "+13 HRS",
    timeZone: "Pacific/Tongatapu",
  },
  {
    city: "Oslo",
    countryCode: "NO",
    country: "Norway",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Oslo",
  },
  {
    city: "Ottawa",
    countryCode: "CA",
    country: "Canada",
    gmtOffset: "-4 HRS",
    timeZone: "America/Toronto",
  },
  {
    city: "Ouagadougou",
    countryCode: "BF",
    country: "Burkina Faso",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Ouagadougou",
  },
  {
    city: "Palikir",
    countryCode: "FM",
    country: "Micronesia",
    gmtOffset: "+11 HRS",
    timeZone: "Pacific/Pohnpei",
  },
  {
    city: "Panama City",
    countryCode: "PA",
    country: "Panama",
    gmtOffset: "-5 HRS",
    timeZone: "America/Panama",
  },
  {
    city: "Paramaribo",
    countryCode: "SR",
    country: "Suriname",
    gmtOffset: "-3 HRS",
    timeZone: "America/Paramaribo",
  },
  {
    city: "Paris",
    countryCode: "FR",
    country: "France",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Paris",
  },
  {
    city: "Phnom Penh",
    countryCode: "KH",
    country: "Cambodia",
    gmtOffset: "+7 HRS",
    timeZone: "Asia/Phnom_Penh",
  },
  {
    city: "Podgorica",
    countryCode: "ME",
    country: "Montenegro",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Podgorica",
  },
  {
    city: "Port-au-Prince",
    countryCode: "HT",
    country: "Haiti",
    gmtOffset: "-4 HRS",
    timeZone: "America/Port-au-Prince",
  },
  {
    city: "Port Louis",
    countryCode: "MU",
    country: "Mauritius",
    gmtOffset: "+4 HRS",
    timeZone: "Indian/Mauritius",
  },
  {
    city: "Port Moresby",
    countryCode: "PG",
    country: "Papua New Guinea",
    gmtOffset: "+10 HRS",
    timeZone: "Pacific/Port_Moresby",
  },
  {
    city: "Port of Spain",
    countryCode: "TT",
    country: "Trinidad and Tobago",
    gmtOffset: "-4 HRS",
    timeZone: "America/Port_of_Spain",
  },
  {
    city: "Port Vila",
    countryCode: "VU",
    country: "Vanuatu",
    gmtOffset: "+11 HRS",
    timeZone: "Pacific/Efate",
  },
  {
    city: "Porto-Novo",
    countryCode: "BJ",
    country: "Benin",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Porto-Novo",
  },
  {
    city: "Praia",
    countryCode: "CV",
    country: "Cabo Verde",
    gmtOffset: "-1 HRS",
    timeZone: "Atlantic/Cape_Verde",
  },
  {
    city: "Prague",
    countryCode: "CZ",
    country: "Czechia",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Prague",
  },
  {
    city: "Pyongyang",
    countryCode: "KP",
    country: "North Korea",
    gmtOffset: "+9 HRS",
    timeZone: "Asia/Pyongyang",
  },
  {
    city: "Quito",
    countryCode: "EC",
    country: "Ecuador",
    gmtOffset: "-5 HRS",
    timeZone: "America/Guayaquil",
  },
  {
    city: "Rabat",
    countryCode: "MA",
    country: "Morocco",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Casablanca",
  },
  {
    city: "Ramallah",
    countryCode: "PS",
    country: "Palestine",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Gaza",
  },
  {
    city: "Reykjavik",
    countryCode: "IS",
    country: "Iceland",
    gmtOffset: "+0 HRS",
    timeZone: "Atlantic/Reykjavik",
  },
  {
    city: "Riga",
    countryCode: "LV",
    country: "Latvia",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Riga",
  },
  {
    city: "Riyadh",
    countryCode: "SA",
    country: "Saudi Arabia",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Riyadh",
  },
  {
    city: "Rome",
    countryCode: "IT",
    country: "Italy",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Rome",
  },
  {
    city: "Roseau",
    countryCode: "DM",
    country: "Dominica",
    gmtOffset: "-4 HRS",
    timeZone: "America/Dominica",
  },
  {
    city: "San José",
    countryCode: "CR",
    country: "Costa Rica",
    gmtOffset: "-6 HRS",
    timeZone: "America/Costa_Rica",
  },
  {
    city: "San Marino",
    countryCode: "SM",
    country: "San Marino",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/San_Marino",
  },
  {
    city: "San Salvador",
    countryCode: "SV",
    country: "El Salvador",
    gmtOffset: "-6 HRS",
    timeZone: "America/El_Salvador",
  },
  {
    city: "Sana'a",
    countryCode: "YE",
    country: "Yemen",
    gmtOffset: "+3 HRS",
    timeZone: "Asia/Aden",
  },
  {
    city: "Santiago",
    countryCode: "CL",
    country: "Chile",
    gmtOffset: "-4 HRS",
    timeZone: "America/Santiago",
  },
  {
    city: "Santo Domingo",
    countryCode: "DO",
    country: "Dominican Republic",
    gmtOffset: "-4 HRS",
    timeZone: "America/Santo_Domingo",
  },
  {
    city: "São Tomé",
    countryCode: "ST",
    country: "São Tomé and Príncipe",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Sao_Tome",
  },
  {
    city: "Sarajevo",
    countryCode: "BA",
    country: "Bosnia and Herzegovina",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Sarajevo",
  },
  {
    city: "Seoul",
    countryCode: "KR",
    country: "South Korea",
    gmtOffset: "+9 HRS",
    timeZone: "Asia/Seoul",
  },
  {
    city: "Singapore",
    countryCode: "SG",
    country: "Singapore",
    gmtOffset: "+8 HRS",
    timeZone: "Asia/Singapore",
  },
  {
    city: "Skopje",
    countryCode: "MK",
    country: "North Macedonia",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Skopje",
  },
  {
    city: "Sofia",
    countryCode: "BG",
    country: "Bulgaria",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Sofia",
  },
  {
    city: "Stockholm",
    countryCode: "SE",
    country: "Sweden",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Stockholm",
  },
  {
    city: "Sucre",
    countryCode: "BO",
    country: "Bolivia",
    gmtOffset: "-4 HRS",
    timeZone: "America/La_Paz",
  },
  {
    city: "Suva",
    countryCode: "FJ",
    country: "Fiji",
    gmtOffset: "+12 HRS",
    timeZone: "Pacific/Fiji",
  },
  {
    city: "Tallinn",
    countryCode: "EE",
    country: "Estonia",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Tallinn",
  },
  {
    city: "Tashkent",
    countryCode: "UZ",
    country: "Uzbekistan",
    gmtOffset: "+5 HRS",
    timeZone: "Asia/Tashkent",
  },
  {
    city: "Tbilisi",
    countryCode: "GE",
    country: "Georgia",
    gmtOffset: "+4 HRS",
    timeZone: "Asia/Tbilisi",
  },
  {
    city: "Tegucigalpa",
    countryCode: "HN",
    country: "Honduras",
    gmtOffset: "-6 HRS",
    timeZone: "America/Tegucigalpa",
  },
  {
    city: "Tehran",
    countryCode: "IR",
    country: "Iran",
    gmtOffset: "+3:30 HRS",
    timeZone: "Asia/Tehran",
  },
  {
    city: "Thimphu",
    countryCode: "BT",
    country: "Bhutan",
    gmtOffset: "+6 HRS",
    timeZone: "Asia/Thimphu",
  },
  {
    city: "Tokyo",
    countryCode: "JP",
    country: "Japan",
    gmtOffset: "+9 HRS",
    timeZone: "Asia/Tokyo",
  },
  {
    city: "Tripoli",
    countryCode: "LY",
    country: "Libya",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Tripoli",
  },
  {
    city: "Tunis",
    countryCode: "TN",
    country: "Tunisia",
    gmtOffset: "+1 HRS",
    timeZone: "Africa/Tunis",
  },
  {
    city: "Ulaanbaatar",
    countryCode: "MN",
    country: "Mongolia",
    gmtOffset: "+8 HRS",
    timeZone: "Asia/Ulaanbaatar",
  },
  {
    city: "Vaduz",
    countryCode: "LI",
    country: "Liechtenstein",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Vaduz",
  },
  {
    city: "Valletta",
    countryCode: "MT",
    country: "Malta",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Malta",
  },
  {
    city: "Vatican City",
    countryCode: "VA",
    country: "Vatican City",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Vatican",
  },
  {
    city: "Vientiane",
    countryCode: "LA",
    country: "Laos",
    gmtOffset: "+7 HRS",
    timeZone: "Asia/Vientiane",
  },
  {
    city: "Victoria",
    countryCode: "SC",
    country: "Seychelles",
    gmtOffset: "+4 HRS",
    timeZone: "Indian/Mahe",
  },
  {
    city: "Vienna",
    countryCode: "AT",
    country: "Austria",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Vienna",
  },
  {
    city: "Vilnius",
    countryCode: "LT",
    country: "Lithuania",
    gmtOffset: "+3 HRS",
    timeZone: "Europe/Vilnius",
  },
  {
    city: "Warsaw",
    countryCode: "PL",
    country: "Poland",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Warsaw",
  },
  {
    city: "Washington, D.C.",
    countryCode: "US",
    country: "USA",
    gmtOffset: "-4 HRS",
    timeZone: "America/New_York",
  },
  {
    city: "Wellington",
    countryCode: "NZ",
    country: "New Zealand",
    gmtOffset: "+12 HRS",
    timeZone: "Pacific/Auckland",
  },
  {
    city: "Windhoek",
    countryCode: "NA",
    country: "Namibia",
    gmtOffset: "+2 HRS",
    timeZone: "Africa/Windhoek",
  },
  {
    city: "Yamoussoukro",
    countryCode: "CI",
    country: "Côte d'Ivoire",
    gmtOffset: "+0 HRS",
    timeZone: "Africa/Abidjan",
  },
  {
    city: "Yaren",
    countryCode: "NR",
    country: "Nauru",
    gmtOffset: "+12 HRS",
    timeZone: "Pacific/Nauru",
  },
  {
    city: "Yerevan",
    countryCode: "AM",
    country: "Armenia",
    gmtOffset: "+4 HRS",
    timeZone: "Asia/Yerevan",
  },
  {
    city: "Zagreb",
    countryCode: "HR",
    country: "Croatia",
    gmtOffset: "+2 HRS",
    timeZone: "Europe/Zagreb",
  },
];

